name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false
    
    
    
    
    
    

# /*
#     - name: Edit file
#       run: chmod +x /home/runner/work/flexjob/flexjob/scripts/script.sh
    
#     - name: connect with GCP
#       uses: google-github-actions/setup-gcloud@master
#       with:
#         service_account_key: ${{ secrets.GCP_SA_KEY }}
#         export_default_credentials: true

#     - name: Setup Terraform
#       uses: hashicorp/setup-terraform@v1
   
#     - name: Initialize terraform
#       run: terraform init
#       env: 
#          GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}
         

#     # Generates an execution plan for Terraform
#     - name: Terraform Plan
#       run: terraform plan
#       env:
#         GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}

         
#     - name: Terraform apply
#       run: terraform apply -auto-approve 
#       env: 
#          GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}
#  */
